// GENERATED — do not edit by hand.
//
// Regenerate with scripts/gen_countries.js, which reads the names out of ICU rather than
// transcribing them. Source: ISO 3166-1 alpha-2 via Intl.DisplayNames (en, ar).
//
// Why the full list: the sign-up country picker used to offer six countries — US, CA, SA,
// QA, AE, GB — because the list was written by hand next to the ADDRESS FORMAT rules, and
// those rules are only known for a handful. But the two are different questions. The
// backend has always accepted any ISO country (@IsISO31661Alpha2 on RegisterDto) and has
// always had a permissive address format for countries whose rules it does not know, so
// the client was narrower than the server for no reason. Wasiati sells globally; someone
// in Malaysia, Indonesia, Pakistan or Nigeria could not enter where they live.
//
// Address FORMAT rules stay a short hand-maintained list in address_rules.dart. That is
// correct: we only know the postcode and area conventions for a few places, and everyone
// else gets the permissive default.

/// One ISO 3166-1 alpha-2 country and its display name per supported locale.
class Country {
  const Country(this.code, this.en, this.ar);
  final String code;
  final String en;
  final String ar;

  /// The name for the active locale. Arabic for 'ar', English otherwise — the two
  /// locales the app ships.
  String nameFor(String languageCode) => languageCode == 'ar' ? ar : en;
}

/// Every ISO 3166-1 alpha-2 country, 267 of them, ordered by code.
/// Sort for display with [countriesSortedFor], which orders by the localized name.
const kCountries = <Country>[
  Country('AD', 'Andorra', 'أندورا'),
  Country('AE', 'United Arab Emirates', 'الإمارات العربية المتحدة'),
  Country('AF', 'Afghanistan', 'أفغانستان'),
  Country('AG', 'Antigua & Barbuda', 'أنتيغوا وبربودا'),
  Country('AI', 'Anguilla', 'أنغويلا'),
  Country('AL', 'Albania', 'ألبانيا'),
  Country('AM', 'Armenia', 'أرمينيا'),
  Country('AN', 'Curaçao', 'كوراساو'),
  Country('AO', 'Angola', 'أنغولا'),
  Country('AQ', 'Antarctica', 'أنتاركتيكا'),
  Country('AR', 'Argentina', 'الأرجنتين'),
  Country('AS', 'American Samoa', 'ساموا الأمريكية'),
  Country('AT', 'Austria', 'النمسا'),
  Country('AU', 'Australia', 'أستراليا'),
  Country('AW', 'Aruba', 'أروبا'),
  Country('AX', 'Åland Islands', 'جزر آلاند'),
  Country('AZ', 'Azerbaijan', 'أذربيجان'),
  Country('BA', 'Bosnia & Herzegovina', 'البوسنة والهرسك'),
  Country('BB', 'Barbados', 'بربادوس'),
  Country('BD', 'Bangladesh', 'بنغلاديش'),
  Country('BE', 'Belgium', 'بلجيكا'),
  Country('BF', 'Burkina Faso', 'بوركينا فاسو'),
  Country('BG', 'Bulgaria', 'بلغاريا'),
  Country('BH', 'Bahrain', 'البحرين'),
  Country('BI', 'Burundi', 'بوروندي'),
  Country('BJ', 'Benin', 'بنين'),
  Country('BL', 'St. Barthélemy', 'سان بارتليمي'),
  Country('BM', 'Bermuda', 'برمودا'),
  Country('BN', 'Brunei', 'بروناي'),
  Country('BO', 'Bolivia', 'بوليفيا'),
  Country('BQ', 'Caribbean Netherlands', 'هولندا الكاريبية'),
  Country('BR', 'Brazil', 'البرازيل'),
  Country('BS', 'Bahamas', 'جزر البهاما'),
  Country('BT', 'Bhutan', 'بوتان'),
  Country('BU', 'Myanmar (Burma)', 'ميانمار (بورما)'),
  Country('BV', 'Bouvet Island', 'جزيرة بوفيه'),
  Country('BW', 'Botswana', 'بوتسوانا'),
  Country('BY', 'Belarus', 'بيلاروس'),
  Country('BZ', 'Belize', 'بليز'),
  Country('CA', 'Canada', 'كندا'),
  Country('CC', 'Cocos (Keeling) Islands', 'جزر كوكوس (كيلينغ)'),
  Country('CD', 'Congo - Kinshasa', 'الكونغو - كينشاسا'),
  Country('CF', 'Central African Republic', 'جمهورية أفريقيا الوسطى'),
  Country('CG', 'Congo - Brazzaville', 'الكونغو - برازافيل'),
  Country('CH', 'Switzerland', 'سويسرا'),
  Country('CI', 'Côte d’Ivoire', 'ساحل العاج'),
  Country('CK', 'Cook Islands', 'جزر كوك'),
  Country('CL', 'Chile', 'تشيلي'),
  Country('CM', 'Cameroon', 'الكاميرون'),
  Country('CN', 'China', 'الصين'),
  Country('CO', 'Colombia', 'كولومبيا'),
  Country('CQ', 'Sark', 'سارك'),
  Country('CR', 'Costa Rica', 'كوستاريكا'),
  Country('CS', 'Serbia', 'صربيا'),
  Country('CU', 'Cuba', 'كوبا'),
  Country('CV', 'Cape Verde', 'الرأس الأخضر'),
  Country('CW', 'Curaçao', 'كوراساو'),
  Country('CX', 'Christmas Island', 'جزيرة كريسماس'),
  Country('CY', 'Cyprus', 'قبرص'),
  Country('CZ', 'Czechia', 'التشيك'),
  Country('DD', 'Germany', 'ألمانيا'),
  Country('DE', 'Germany', 'ألمانيا'),
  Country('DJ', 'Djibouti', 'جيبوتي'),
  Country('DK', 'Denmark', 'الدانمرك'),
  Country('DM', 'Dominica', 'دومينيكا'),
  Country('DO', 'Dominican Republic', 'جمهورية الدومينيكان'),
  Country('DY', 'Benin', 'بنين'),
  Country('DZ', 'Algeria', 'الجزائر'),
  Country('EC', 'Ecuador', 'الإكوادور'),
  Country('EE', 'Estonia', 'إستونيا'),
  Country('EG', 'Egypt', 'مصر'),
  Country('EH', 'Western Sahara', 'الصحراء الغربية'),
  Country('ER', 'Eritrea', 'إريتريا'),
  Country('ES', 'Spain', 'إسبانيا'),
  Country('ET', 'Ethiopia', 'إثيوبيا'),
  Country('FI', 'Finland', 'فنلندا'),
  Country('FJ', 'Fiji', 'فيجي'),
  Country('FK', 'Falkland Islands', 'جزر فوكلاند'),
  Country('FM', 'Micronesia', 'ميكرونيزيا'),
  Country('FO', 'Faroe Islands', 'جزر فارو'),
  Country('FR', 'France', 'فرنسا'),
  Country('FX', 'France', 'فرنسا'),
  Country('GA', 'Gabon', 'الغابون'),
  Country('GB', 'United Kingdom', 'المملكة المتحدة'),
  Country('GD', 'Grenada', 'غرينادا'),
  Country('GE', 'Georgia', 'جورجيا'),
  Country('GF', 'French Guiana', 'غويانا الفرنسية'),
  Country('GG', 'Guernsey', 'غيرنزي'),
  Country('GH', 'Ghana', 'غانا'),
  Country('GI', 'Gibraltar', 'جبل طارق'),
  Country('GL', 'Greenland', 'غرينلاند'),
  Country('GM', 'Gambia', 'غامبيا'),
  Country('GN', 'Guinea', 'غينيا'),
  Country('GP', 'Guadeloupe', 'غوادلوب'),
  Country('GQ', 'Equatorial Guinea', 'غينيا الاستوائية'),
  Country('GR', 'Greece', 'اليونان'),
  Country('GS', 'South Georgia & South Sandwich Islands', 'جورجيا الجنوبية وجزر ساندويتش الجنوبية'),
  Country('GT', 'Guatemala', 'غواتيمالا'),
  Country('GU', 'Guam', 'غوام'),
  Country('GW', 'Guinea-Bissau', 'غينيا بيساو'),
  Country('GY', 'Guyana', 'غيانا'),
  Country('HK', 'Hong Kong SAR China', 'هونغ كونغ الصينية (منطقة إدارية خاصة)'),
  Country('HM', 'Heard & McDonald Islands', 'جزيرة هيرد وجزر ماكدونالد'),
  Country('HN', 'Honduras', 'هندوراس'),
  Country('HR', 'Croatia', 'كرواتيا'),
  Country('HT', 'Haiti', 'هايتي'),
  Country('HU', 'Hungary', 'هنغاريا'),
  Country('HV', 'Burkina Faso', 'بوركينا فاسو'),
  Country('ID', 'Indonesia', 'إندونيسيا'),
  Country('IE', 'Ireland', 'أيرلندا'),
  Country('IL', 'Israel', 'إسرائيل'),
  Country('IM', 'Isle of Man', 'جزيرة مان'),
  Country('IN', 'India', 'الهند'),
  Country('IO', 'British Indian Ocean Territory', 'الإقليم البريطاني في المحيط الهندي'),
  Country('IQ', 'Iraq', 'العراق'),
  Country('IR', 'Iran', 'إيران'),
  Country('IS', 'Iceland', 'آيسلندا'),
  Country('IT', 'Italy', 'إيطاليا'),
  Country('JE', 'Jersey', 'جيرسي'),
  Country('JM', 'Jamaica', 'جامايكا'),
  Country('JO', 'Jordan', 'الأردن'),
  Country('JP', 'Japan', 'اليابان'),
  Country('KE', 'Kenya', 'كينيا'),
  Country('KG', 'Kyrgyzstan', 'قيرغيزستان'),
  Country('KH', 'Cambodia', 'كمبوديا'),
  Country('KI', 'Kiribati', 'كيريباتي'),
  Country('KM', 'Comoros', 'جزر القمر'),
  Country('KN', 'St. Kitts & Nevis', 'سانت كيتس ونيفيس'),
  Country('KP', 'North Korea', 'كوريا الشمالية'),
  Country('KR', 'South Korea', 'كوريا الجنوبية'),
  Country('KW', 'Kuwait', 'الكويت'),
  Country('KY', 'Cayman Islands', 'جزر كايمان'),
  Country('KZ', 'Kazakhstan', 'كازاخستان'),
  Country('LA', 'Laos', 'لاوس'),
  Country('LB', 'Lebanon', 'لبنان'),
  Country('LC', 'St. Lucia', 'سانت لوسيا'),
  Country('LI', 'Liechtenstein', 'ليختنشتاين'),
  Country('LK', 'Sri Lanka', 'سريلانكا'),
  Country('LR', 'Liberia', 'ليبيريا'),
  Country('LS', 'Lesotho', 'ليسوتو'),
  Country('LT', 'Lithuania', 'ليتوانيا'),
  Country('LU', 'Luxembourg', 'لوكسمبورغ'),
  Country('LV', 'Latvia', 'لاتفيا'),
  Country('LY', 'Libya', 'ليبيا'),
  Country('MA', 'Morocco', 'المغرب'),
  Country('MC', 'Monaco', 'موناكو'),
  Country('MD', 'Moldova', 'مولدوفا'),
  Country('ME', 'Montenegro', 'الجبل الأسود'),
  Country('MF', 'St. Martin', 'سان مارتن'),
  Country('MG', 'Madagascar', 'مدغشقر'),
  Country('MH', 'Marshall Islands', 'جزر مارشال'),
  Country('MK', 'North Macedonia', 'مقدونيا الشمالية'),
  Country('ML', 'Mali', 'مالي'),
  Country('MM', 'Myanmar (Burma)', 'ميانمار (بورما)'),
  Country('MN', 'Mongolia', 'منغوليا'),
  Country('MO', 'Macao SAR China', 'منطقة ماكاو الإدارية الخاصة'),
  Country('MP', 'Northern Mariana Islands', 'جزر ماريانا الشمالية'),
  Country('MQ', 'Martinique', 'جزر المارتينيك'),
  Country('MR', 'Mauritania', 'موريتانيا'),
  Country('MS', 'Montserrat', 'مونتسرات'),
  Country('MT', 'Malta', 'مالطا'),
  Country('MU', 'Mauritius', 'موريشيوس'),
  Country('MV', 'Maldives', 'جزر المالديف'),
  Country('MW', 'Malawi', 'ملاوي'),
  Country('MX', 'Mexico', 'المكسيك'),
  Country('MY', 'Malaysia', 'ماليزيا'),
  Country('MZ', 'Mozambique', 'موزمبيق'),
  Country('NA', 'Namibia', 'ناميبيا'),
  Country('NC', 'New Caledonia', 'كاليدونيا الجديدة'),
  Country('NE', 'Niger', 'النيجر'),
  Country('NF', 'Norfolk Island', 'جزيرة نورفولك'),
  Country('NG', 'Nigeria', 'نيجيريا'),
  Country('NH', 'Vanuatu', 'فانواتو'),
  Country('NI', 'Nicaragua', 'نيكاراغوا'),
  Country('NL', 'Netherlands', 'هولندا'),
  Country('NO', 'Norway', 'النرويج'),
  Country('NP', 'Nepal', 'نيبال'),
  Country('NR', 'Nauru', 'ناورو'),
  Country('NU', 'Niue', 'نيوي'),
  Country('NZ', 'New Zealand', 'نيوزيلندا'),
  Country('OM', 'Oman', 'عُمان'),
  Country('PA', 'Panama', 'بنما'),
  Country('PE', 'Peru', 'بيرو'),
  Country('PF', 'French Polynesia', 'بولينيزيا الفرنسية'),
  Country('PG', 'Papua New Guinea', 'بابوا غينيا الجديدة'),
  Country('PH', 'Philippines', 'الفلبين'),
  Country('PK', 'Pakistan', 'باكستان'),
  Country('PL', 'Poland', 'بولندا'),
  Country('PM', 'St. Pierre & Miquelon', 'سان بيير ومكويلون'),
  Country('PN', 'Pitcairn Islands', 'جزر بيتكيرن'),
  Country('PR', 'Puerto Rico', 'بورتوريكو'),
  Country('PS', 'Palestinian Territories', 'الأراضي الفلسطينية'),
  Country('PT', 'Portugal', 'البرتغال'),
  Country('PW', 'Palau', 'بالاو'),
  Country('PY', 'Paraguay', 'باراغواي'),
  Country('QA', 'Qatar', 'قطر'),
  Country('RE', 'Réunion', 'روينيون'),
  Country('RH', 'Zimbabwe', 'زيمبابوي'),
  Country('RO', 'Romania', 'رومانيا'),
  Country('RS', 'Serbia', 'صربيا'),
  Country('RU', 'Russia', 'روسيا'),
  Country('RW', 'Rwanda', 'رواندا'),
  Country('SA', 'Saudi Arabia', 'المملكة العربية السعودية'),
  Country('SB', 'Solomon Islands', 'جزر سليمان'),
  Country('SC', 'Seychelles', 'سيشل'),
  Country('SD', 'Sudan', 'السودان'),
  Country('SE', 'Sweden', 'السويد'),
  Country('SG', 'Singapore', 'سنغافورة'),
  Country('SH', 'St. Helena', 'سانت هيلينا'),
  Country('SI', 'Slovenia', 'سلوفينيا'),
  Country('SJ', 'Svalbard & Jan Mayen', 'سفالبارد وجان ماين'),
  Country('SK', 'Slovakia', 'سلوفاكيا'),
  Country('SL', 'Sierra Leone', 'سيراليون'),
  Country('SM', 'San Marino', 'سان مارينو'),
  Country('SN', 'Senegal', 'السنغال'),
  Country('SO', 'Somalia', 'الصومال'),
  Country('SR', 'Suriname', 'سورينام'),
  Country('SS', 'South Sudan', 'جنوب السودان'),
  Country('ST', 'São Tomé & Príncipe', 'ساو تومي وبرينسيبي'),
  Country('SU', 'Russia', 'روسيا'),
  Country('SV', 'El Salvador', 'السلفادور'),
  Country('SX', 'Sint Maarten', 'سانت مارتن'),
  Country('SY', 'Syria', 'سوريا'),
  Country('SZ', 'Eswatini', 'إسواتيني'),
  Country('TC', 'Turks & Caicos Islands', 'جزر توركس وكايكوس'),
  Country('TD', 'Chad', 'تشاد'),
  Country('TF', 'French Southern Territories', 'الأقاليم الجنوبية الفرنسية'),
  Country('TG', 'Togo', 'توغو'),
  Country('TH', 'Thailand', 'تايلاند'),
  Country('TJ', 'Tajikistan', 'طاجيكستان'),
  Country('TK', 'Tokelau', 'توكيلاو'),
  Country('TL', 'Timor-Leste', 'تيمور - ليشتي'),
  Country('TM', 'Turkmenistan', 'تركمانستان'),
  Country('TN', 'Tunisia', 'تونس'),
  Country('TO', 'Tonga', 'تونغا'),
  Country('TP', 'Timor-Leste', 'تيمور - ليشتي'),
  Country('TR', 'Türkiye', 'تركيا'),
  Country('TT', 'Trinidad & Tobago', 'ترينيداد وتوباغو'),
  Country('TV', 'Tuvalu', 'توفالو'),
  Country('TW', 'Taiwan', 'تايوان'),
  Country('TZ', 'Tanzania', 'تنزانيا'),
  Country('UA', 'Ukraine', 'أوكرانيا'),
  Country('UG', 'Uganda', 'أوغندا'),
  Country('UK', 'United Kingdom', 'المملكة المتحدة'),
  Country('UM', 'U.S. Outlying Islands', 'جزر الولايات المتحدة النائية'),
  Country('US', 'United States', 'الولايات المتحدة'),
  Country('UY', 'Uruguay', 'أورغواي'),
  Country('UZ', 'Uzbekistan', 'أوزبكستان'),
  Country('VA', 'Vatican City', 'الفاتيكان'),
  Country('VC', 'St. Vincent & Grenadines', 'سانت فنسنت وجزر غرينادين'),
  Country('VD', 'Vietnam', 'فيتنام'),
  Country('VE', 'Venezuela', 'فنزويلا'),
  Country('VG', 'British Virgin Islands', 'جزر فيرجن البريطانية'),
  Country('VI', 'U.S. Virgin Islands', 'جزر فيرجن الأمريكية'),
  Country('VN', 'Vietnam', 'فيتنام'),
  Country('VU', 'Vanuatu', 'فانواتو'),
  Country('WF', 'Wallis & Futuna', 'جزر والس وفوتونا'),
  Country('WS', 'Samoa', 'ساموا'),
  Country('XK', 'Kosovo', 'كوسوفو'),
  Country('YD', 'Yemen', 'اليمن'),
  Country('YE', 'Yemen', 'اليمن'),
  Country('YT', 'Mayotte', 'مايوت'),
  Country('YU', 'Serbia', 'صربيا'),
  Country('ZA', 'South Africa', 'جنوب أفريقيا'),
  Country('ZM', 'Zambia', 'زامبيا'),
  Country('ZR', 'Congo - Kinshasa', 'الكونغو - كينشاسا'),
  Country('ZW', 'Zimbabwe', 'زيمبابوي'),
];

/// The countries ordered by their name in [languageCode] — the order to show a human.
/// Code order is meaningless to a reader, and alphabetical-by-English is wrong in Arabic.
List<Country> countriesSortedFor(String languageCode) {
  final list = [...kCountries];
  list.sort((a, b) => a.nameFor(languageCode).compareTo(b.nameFor(languageCode)));
  return list;
}

/// Lookup by ISO code, or null when the code is not a country we know.
Country? countryFor(String code) {
  final upper = code.toUpperCase();
  for (final c in kCountries) {
    if (c.code == upper) return c;
  }
  return null;
}
